language: ruby
rvm:
- 2.4.5
script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rspec
env:
  matrix:
    secure: NXOgnEA3fdIL2umj0eZ4b0bnKDD4iy3ITLW27i01rGEPVmUJIDh5bscY1+QaxXLUe1SlLV+0ACBVq+cw6z8EfCksNoN4uMw4/J681jXO4tpDQO9K45F0o8uor0vv21HIvb94fe554EdhITCwrPsZV9VhqSVmPayi9jy5GloIWxUBK6fAK3pPqF6W137CQvjdoMIcFJllKNTIZJ/011Qa1/WU4+yLvAnT+i8QyjtxRC8GKs0kCmQFUcXd6T7vQEXRWDVz+mqCrX6+MOyAqpF3rajKqjDTHI9wPn35guiTMn+ISOm5mkfOmJnQXl/lcY4ouZuypzUbqsuT5srF7qmgUITeyuV+7U4JMP+GD+dNfVTUTh8CsucODSRfYAic5f70j1QTCryGm5yoiE3Wm0WTASqMerwLYrr/OJzQBQl4zmXanH/u8+u2SW5apZV/4bKT41AEAYJn2fyLfIcm+yvM06OneGcAyzhAdj9jHhZmHwYCcOQOS6HG/nhVHyBPEQHN7OEZXta6OlLuSCBMuPvawMu/xufB5HcRg0okaNaHzf84Q13GQV4fx4fOkaf2PvNf0kWb1SW76I/Aftpya+dzea+hpheHwdO2hJCoYd6HkKKl30jMcS9ytNA/HnLGgmeTFPmXzwpJEXaaSjWZhovVII2yaZeoE0TP3IdgYTqCOto=
